# -*- coding: utf-8 -*-
"""Task Week 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l4dMlooC9-je3EYUOjgBqHtNnxu8f_V6

Name: Syed Sameer Rizvi
------------------------------
AICP Internship Task Week 1
-----------------------
"""

import numpy as np

"""Q1) Write a NumPy program to create an array of all even integers from 30 to 70
--------------------------------------------------------------
"""

arr = np.arange(30,71,2)
print(arr)

"""Q2) Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
---------------------------------------

"""

arr = np.random.randn(15)
print(arr)

"""Q3) How to compute the cross-product of two matrices in NumPy?
-------------------------------------------------------
"""

mat_A = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_B = np.array([[1,4,5],[6,3,2],[10,2,3]])
mat_C = np.cross(mat_A,mat_B)
print(mat_C)

"""Q4) How to compute the determinant of an array using NumPy?
-------------------------------------------------
"""

arr = np.array([[1,2],[4,5]])
det_arr = np.linalg.det(arr)
print(round(det_arr,2))

"""Q5) How to create a 3x3x3 array with random values using NumPy?
----------------------------------------

"""

dimensions = (3,3,3)
mat_A = np.random.randint(1,15,size=dimensions)
print(mat_A)

"""Q6) How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?
---------------------------------------------
"""

dimensions = (5,5)
mat_A = np.random.randint(1,25,size=dimensions)
print(mat_A)

result_1 = np.min(mat_A)
print("The minimun value is: ",result_1)

result_2 = np.max(mat_A)
print("The maximum value is: ",result_2)

"""Q7) How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?
---------------------------------------------


"""

arr = np.array([[1,4,5],[6,3,2],[10,2,3]])
mean_arr = np.mean(arr,axis=1)
var_arr = np.var(arr,axis=1)
std_arr = np.std(arr,axis=1)

print("The mean is: ",mean_arr)
print("The variance is: ",var_arr)
print("The standard deviation is: ",std_arr)